apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: kiii-project
data:
  DEBUG: "1"
  POSTGRES_NAME: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: kiii-project
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: kiii-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: slavkovskis/car-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: static-files
              mountPath: /app/static
      volumes:  
        - name: static-files
          emptyDir: {}
